TaskAssignment/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views
from django.contrib.auth.decorators import login_required, permission_required

app_name='tasks'

urlpatterns = [
    url(r'^$',login_required(views.HomePageView.as_view()),name="home_page"),
    url(r'^add/task$',login_required(views.CreateTaskView.as_view()),name="createTask"),
    url(r'^task/(?P<pk>[0-9]+)/$',login_required(views.DetailTaskView),name="detailTask"),
    url(r'^add/team$',login_required(views.CreateTeamView.as_view()),name="createTeam"),
    url(r'^team/(?P<pk>[0-9]+)/members/$',login_required(views.AddTeamMemView.as_view()),name="team_members"),
    url(r'^team/(?P<id_team>[0-9]+)/tasks$',login_required(views.CardDetialView),name="taskList"),
]

TaskList/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth.decorators import login_required, permission_required

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('TaskAssignment.urls')),
    url(r'^logout/$','django.contrib.auth.views.logout', {'next_page': '/accounts/login/'},name='logout'),
]


# (r'^login/$',
#     'django.contrib.auth.views.login', {'template_name': 'login.html'}
# )

TaskAssignment/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
# Create your models here.

class TeamList(models.Model):
    name = models.CharField(unique=True,max_length=50)
    description = models.CharField(max_length=120)
    def get_absolute_url(self): 
        return reverse('tasks:team_members',kwargs={'pk':self.pk})

    def __str__(self):
        return self.name
    #member = models.ForeignKey(User,on_delete=CASCADE)


# class Report(models.Model):
#     user_id = models.ForeignKey(User, related_name="task_submittedBy")
#     task_id = models.ManyToManyField(TaskList)

class TaskList(models.Model):
    team =  models.ForeignKey(TeamList,on_delete=models.CASCADE)
    task = models.CharField(max_length=30)
    assign_date = models.DateField(auto_now=False, auto_now_add=True)
    assignedBy = models.ForeignKey(User, related_name="task_assignedBy")
    assignedTo = models.ForeignKey(User, related_name="task_assignedTo")
    # currentStauts =  models.IntegerField()
    STATUS_CHOICES = (
        ('Pending'  ,'Pending'),
        ('Started'  ,'Started'),
        ('Completed','Completed')
    )
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='Pending',
        blank=True,
    )
    
    def get_absolute_url(self): #use cases>?
        return reverse('tasks:home_page')

    def __str__(self):
        return self.task

class TeamMembers(models.Model):
    team_name = models.ForeignKey(TeamList,on_delete=models.CASCADE)
    team_member = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return str(self.team_name)

    def get_absolute_url(self): 
        return reverse('tasks:team_members',kwargs={'pk':self.pk})

    

TaskAssignment/views.py
from django.views import generic
from django.views.generic import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from .models import TaskList,TeamList,TeamMembers
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate,login
from django.views.generic.base import TemplateView
from django.shortcuts import get_object_or_404
from django.db.models import Count
from django.db.models import Q


class HomePageView(TemplateView):
   
    template_name='TaskAssignment/cards.html'

    def get_context_data(self,**kwargs):
        tasks = TaskList.objects.filter(Q(assignedTo=self.request.user) | Q(assignedBy=self.request.user))
        teams = TeamMembers.objects.filter(team_member=self.request.user)
        
        all_task = tasks.values('team').annotate(Count('task'))#tasks.count()
        pending_task = tasks.filter(status='Pending').values('team').annotate(Count('task'))
        count_list =zip(all_task,pending_task)
        context={
            "tasks" : tasks,
            "teams" : teams,
            "all_task_count":count_list,

        }
        return context

# class DetailTaskView(generic.DetailView):
#     context_object_name = 'all_task'
#     model = TaskList
#     template_name = 'TaskAssignment/taskDetail.html'

def DetailTaskView(request,pk):
    # pk=request.GET.get('id_team')
    if request.method=='POST':
        form_status = request.POST.get('selected_status')
        all_task = TaskList.objects.filter(id=pk).update(status=form_status)
        context={
            'all_task' : all_task
        }
        return redirect(reverse('tasks:home_page'))

    all_task = TaskList.objects.filter(id=pk)
    context={
        'all_task' : all_task
    }
    return render(request,'TaskAssignment/cardDetails.html',context)   
# class CawrdDetialView(generic.ListView):
#     model = TaskList
#     context_object_name = 'all_task'
#     template_name='TaskAssignment/cardDetail.html'
    
#     def get_queryset(self,id_team):
#         # pk=request.get.GET('id_team')      
#         return TaskList.objects.filter(team_id=id_team)

def CardDetialView(request,id_team):
    # pk=request.GET.get('id_team')
    if request.method=='POST':
        form_status = request.GET.get('selected_status')
        all_task = TaskList.objects.filter(id=id_team).update(status=form_status)
        context={
            'all_task' : all_task
        }
        return render(request,'TaskAssignment/cardDetails.html',context)

    all_task = TaskList.objects.filter(team_id=id_team)
    context={
        'all_task' : all_task
    }
    return render(request,'TaskAssignment/cardDetails.html',context)

class CreateTaskView(CreateView):
    model = TaskList
    fields ='__all__'

class CreateTeamView(CreateView):
    model = TeamList
    fields ='__all__'


class AddTeamMemView(CreateView):
    model = TeamMembers
    template_name='TaskAssignment/teamlist_form.html'
    fields='__all__'

class UpdateTaskView(UpdateView):
    model = TaskList
    fields =['status']

templates/TaskAssignment/base.html
<!DOCTYPE html>
<html>
<head>
<title>{% block title%}Home | Task Manager{%endblock%}</title> <!--This can be overwritten-->

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy" type="text/css">
<!--  -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
        <div class="container-fluid">
            
            <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"  href="{% url 'tasks:home_page' %}">Task Manager</a>
            </div>
            
            <!--items-->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{%url 'tasks:createTask' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;All Tasks</a>
                    </li>
                    <li>
                        <a href="#">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Teams</a>
                    </li>
                </ul>
    
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div vlass="form-group">
                        <input type="text" class="form-control" name="q" values="">
                        <button type="submit" class="btn btn-default">Find Task</button>
                    </div>
                </form>
    
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{%url 'tasks:createTask' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add New Task</a>
                    </li>
                    <li>
                        <a href="{%url 'tasks:createTeam' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Create Your Team</a>
                    </li>
                    <li>
                        <a href="{%url 'logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
   
    <div class="container">
     {% block body %}  
     
     {% for obj in teams %}
         <a href="{%url 'tasks:team_members' pk=obj.id%}">{{obj.name}}</p>
     {% endfor %}
         
     {% endblock body %}
    </div>
    
    
</body>

templates/TaskAssignment/cardDetails.html
{% extends 'TaskAssignment/base.html' %}

{% block body %}
    {%if all_task%}
   
        {% for task in all_task%}
            <div class="col">
                <div class="col-md-3">
                  <div class="thumbnail">
                      <h3>Issue : </h3>
                      <h4>{{task.task}}</h4><hr>
                      <h5>Current Status : {{task.status}}</h5>
                      <div class="caption">
                        <p>By : {{task.assignedBy}}<br>
                        ON : {{task.assign_date}}</p>
                        {{task.team}}
                        <form action ="{%url 'tasks:detailTask' task.id%}" method="POST" style="display:inline">
                            {% csrf_token %}
                            <select class="mdb-select md-form" name="selected_status">
                                <option value="" disabled selected>Update Status</option>
                                <option value="Started">Started</option>
                                <option value="Completed">Completed</option>
                                <option value="Pending">Pending</option>
                            </select>
                            <input type="submit" value="Select">
                        </form>
                      </div>
                  </div>
                </div>
            </div>
        
        {%endfor%}
  
    {%endif%}
{% endblock %}

templates/TaskAssignment/cards.html
{% extends 'TaskAssignment/base.html' %}

{% block body %}
    {%if tasks%}
   
        {% for all_task,pending_task in all_task_count%}
            <a href="{%url 'tasks:taskList' all_task.team%}">
            <div class="col">
                <div class="col-md-2">
                  <div class="thumbnail">
                      <h4>Open Issue : {{pending_task.task__count}}/{{all_task.task__count}}</h4><hr>
                      <div class="caption">
                          <p>{{all_task.team}}</p>
                      </div>
                  </div>
                </div>
            </div>
            </a>
        {%endfor%}
  
    {%endif%}
{% endblock %}

templates/TaskAssignment/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small"> {{ field.errors }}</span>
    </div>  
    <div>
        <label class="control-label col-sm-2">{{field.label_tag}}</label>
        <div class="col-sm-10">{{field}}</div>
    </div>
    
</div>
{%endfor%}

templates/TaskAssignment/tasklist_form.html
{%extends 'TaskAssignment/base.html' %}
{% block body %}  
<div class="container-fluid">
    <div class="row">
        <h2>Add new task</h2>
        <div class="col-sm-12 col-md-7">
        <div class="panel panel-defualt">
        <div class="panel-body">

        <form action="" method="POST" enctype="multipart/form-data"> <!--what's enctype-->
            {% csrf_token %} 
            {% include 'TaskAssignment/form-template.html' %}
            <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
            </div>                 
        </form>
        </div>
        </div>
        </div>
    </div>
</div>
{% endblock body %}  

templates/TaskAssignment/teamlist_form.html
{%extends 'TaskAssignment/base.html' %}
{% block body %}  
<div class="container-fluid">
    <div class="row">
        <h2>Add new task</h2>
        <div class="col-sm-12 col-md-7">
        <div class="panel panel-defualt">
        <div class="panel-body">

        <form action="" method="POST" enctype="multipart/form-data"> <!--what's enctype-->
            {% csrf_token %} 
            {% include 'TaskAssignment/form-template.html' %}
            <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-success">Submit</button>
            </div>                 
        </form>
        </div>
        </div>
        </div>
    </div>
</div>
{% endblock body %}  